apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: draftmate-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  selector:
    app: draftmate-backend
