apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: draftmate-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draftmate-db
  template:
    metadata:
      labels:
        app: draftmate-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.backend.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.backend.env.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.backend.env.POSTGRES_DB | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
