apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: draftmate-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: draftmate-db
