{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: draftmate-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/limit-rps: "25"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-connections: "20"
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      # Route API requests for individual microservices to the API Gateway
      - path: /auth/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /query/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /converter/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /enhance/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /drafter/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /lexbot/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /pdf/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /notification/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /subscriptions/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      - path: /case_search/
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
      # Route all other traffic to the Frontend React App
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: {{ $.Values.frontend.service.port }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}