import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import fullLogo from '../assets/FULL_LOGO.svg';

const disclaimerSections = [
    {
        title: '1. No Legal Advice',
        intro: 'Draftmate is a technology platform that provides automated drafting assistance.',
        points: [
            'Draftmate does not provide legal advice.',
            'Draftmate does not create an attorney-client relationship.',
            'Outputs generated by Draftmate are for informational and drafting assistance purposes only.',
        ],
        footer: 'Users must consult a qualified advocate or legal professional before relying on any generated content for legal proceedings.',
    },
    {
        title: '2. No Attorney-Client Relationship',
        intro: 'Use of Draftmate does not establish:',
        points: [
            'Attorney-client relationship',
            'Fiduciary relationship',
            'Legal representation of any kind',
        ],
        footer: 'No communication with Draftmate creates privileged legal communication.',
    },
    {
        title: '3. Accuracy of AI-Generated Content',
        intro: 'Draftmate uses artificial intelligence technology to generate content. While we strive for accuracy:',
        points: [
            'AI-generated outputs may contain errors, omissions, or outdated legal references.',
            'Draftmate does not guarantee completeness, reliability, or suitability for specific legal matters.',
            'Users are solely responsible for reviewing and verifying all generated content before use.',
        ],
    },
    {
        title: '4. Not a Substitute for Professional Advice',
        intro: 'Draftmate is not a substitute for:',
        points: [
            'Licensed advocates',
            'Chartered accountants',
            'Company secretaries',
            'Legal consultants',
        ],
        footer: 'Always seek professional legal advice for case-specific guidance.',
    },
    {
        title: '5. Jurisdictional Limitations',
        intro: 'Laws vary across jurisdictions. Draftmate does not guarantee that generated content complies with:',
        points: [
            'Specific court formats',
            'Local procedural rules',
            'Jurisdiction-specific regulations',
        ],
        footer: 'Users are responsible for ensuring compliance with applicable laws.',
    },
    {
        title: '6. No Liability for Use of Content',
        intro: 'To the maximum extent permitted by law, Draftmate, its directors, officers, employees, affiliates, and shareholders shall not be liable for:',
        points: [
            'Any direct or indirect loss',
            'Legal consequences arising from reliance on generated content',
            'Court rejections or adverse decisions',
            'Financial or reputational damages',
        ],
        footer: 'Use of Draftmate is at your own risk.',
    },
    {
        title: '7. Informational Purpose Only',
        intro: 'Draftmate content is provided for:',
        points: [
            'Drafting assistance',
            'Research support',
            'Educational purposes',
        ],
        footer: 'It is not a research report, certified document, or formal legal opinion.',
    },
    {
        title: '8. Third-Party Services & Links',
        intro: 'Draftmate may integrate with or link to third-party services. We do not control or guarantee:',
        points: [
            'Accuracy of third-party content',
            'Security of third-party platforms',
            'Policies of external websites',
        ],
        footer: 'Users access third-party services at their own risk.',
    },
    {
        title: '9. Service Availability',
        intro: 'We do not guarantee:',
        points: [
            'Uninterrupted access',
            'Error-free operation',
            'Continuous availability',
        ],
        footer: 'Draftmate reserves the right to modify, suspend, or discontinue services without prior notice.',
    },
    {
        title: '10. Indemnification',
        intro: 'By using Draftmate, you agree to indemnify and hold harmless Draftmate Pvt. Ltd., its directors, employees, affiliates, and partners from any claims, damages, liabilities, or legal expenses arising out of:',
        points: [
            'Misuse of the platform',
            'Violation of applicable laws',
            'Reliance on AI-generated outputs',
        ],
    },
    {
        title: '11. Beta Features Disclaimer (If Applicable)',
        intro: 'Certain features may be labeled as "Beta" or "Experimental."',
        points: [
            'Such features are provided "as-is" without warranties and may contain bugs or inaccuracies.',
        ],
    },
    {
        title: '12. Intellectual Property Disclaimer',
        intro: 'Draftmate provides AI-generated templates and drafts.',
        points: [
            'Users are responsible for ensuring they have the right to use generated content.',
            'Draftmate does not guarantee originality against third-party claims.',
        ],
    },
];

const Disclaimer = () => {
    useEffect(() => {
        document.title = 'Disclaimer - DraftMate';
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="bg-slate-50 text-slate-900 font-sans overflow-x-hidden min-h-screen">
            {/* Navigation */}
            <header className="sticky top-0 z-50 flex items-center justify-between whitespace-nowrap border-b border-slate-200/80 bg-white/95 backdrop-blur-md px-6 py-3 lg:px-20">
                <Link to="/" className="flex items-center gap-4">
                    <div className="h-12 flex items-center justify-center hover:opacity-80 transition-opacity">
                        <img src={fullLogo} alt="DraftMate" className="h-full object-contain" />
                    </div>
                </Link>
                <div className="flex items-center gap-4">
                    <Link to="/" className="text-slate-600 hover:text-primary transition-colors font-medium">← Back to Home</Link>
                    <Link to="/login" className="hidden sm:flex items-center justify-center rounded-lg h-10 px-6 bg-primary text-white font-bold hover:bg-primary/90 transition-colors shadow-lg shadow-primary/25">
                        Get Started
                    </Link>
                </div>
            </header>

            {/* Hero Section */}
            <section className="relative py-16 lg:py-24 px-4 overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-br from-amber-50 via-white to-orange-50" />
                <div className="absolute top-20 left-1/4 w-72 h-72 bg-amber-400/20 rounded-full blur-3xl" />
                <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-orange-400/20 rounded-full blur-3xl" />

                <div className="relative z-10 max-w-4xl mx-auto text-center">
                    <div className="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-4 py-2 text-sm font-bold text-amber-700 uppercase tracking-wide mb-8">
                        <span className="material-symbols-outlined text-base">gavel</span>
                        Legal Notice
                    </div>
                    <h1 className="text-4xl md:text-5xl lg:text-6xl font-black leading-tight tracking-tight mb-6">
                        Draftmate <span className="text-primary">Disclaimer</span>
                    </h1>
                    <p className="text-xl text-slate-600 max-w-2xl mx-auto">
                        Please read this disclaimer carefully before using our Services.
                    </p>
                    <p className="text-sm text-slate-400 mt-4">Last Updated: February 19, 2026</p>
                </div>
            </section>

            {/* Intro */}
            <section className="px-4 pb-8">
                <div className="max-w-3xl mx-auto">
                    <div className="bg-white rounded-2xl shadow-md border border-slate-100 p-6 md:p-8">
                        <p className="text-slate-700 leading-relaxed">
                            Draftmate Pvt. Ltd. (&quot;Draftmate&quot;, &quot;we&quot;, &quot;our&quot;, &quot;us&quot;) provides AI-powered legal drafting assistance. By accessing or using Draftmate&apos;s website, applications, extensions, or services (collectively, the &quot;Services&quot;), you agree to the following disclaimers:
                        </p>
                    </div>
                </div>
            </section>

            {/* Disclaimer Sections */}
            <section className="py-8 lg:py-12 px-4">
                <div className="max-w-3xl mx-auto flex flex-col gap-6">
                    {disclaimerSections.map((section, index) => (
                        <div key={index} className="bg-white rounded-2xl shadow-md border border-slate-100 p-6 md:p-8 transition-shadow hover:shadow-lg">
                            <h2 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-3">
                                <span className="flex items-center justify-center w-10 h-10 rounded-xl bg-primary/10 text-primary font-black text-sm">
                                    {index + 1}
                                </span>
                                {section.title.replace(/^\d+\.\s*/, '')}
                            </h2>
                            {section.intro && (
                                <p className="text-slate-600 leading-relaxed mb-4">{section.intro}</p>
                            )}
                            <ul className="space-y-2 mb-4">
                                {section.points.map((point, i) => (
                                    <li key={i} className="flex items-start gap-3 text-slate-600">
                                        <span className="material-symbols-outlined text-primary text-lg mt-0.5 flex-shrink-0">chevron_right</span>
                                        <span className="leading-relaxed">{point}</span>
                                    </li>
                                ))}
                            </ul>
                            {section.footer && (
                                <p className="text-slate-700 font-medium leading-relaxed bg-slate-50 rounded-xl p-4 border border-slate-100">
                                    {section.footer}
                                </p>
                            )}
                        </div>
                    ))}
                </div>
            </section>

            {/* Footer */}
            <footer className="bg-slate-900 text-white py-12 px-4">
                <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
                    <Link to="/" className="flex items-center gap-3">
                        <div className="h-8 bg-white/90 backdrop-blur-sm rounded-full px-4 py-1 shadow-sm">
                            <img src={fullLogo} alt="DraftMate" className="h-full object-contain" />
                        </div>
                    </Link>
                    <div className="flex gap-6">
                        <Link to="/" className="text-slate-400 hover:text-white transition-colors">Home</Link>
                        <Link to="/features" className="text-slate-400 hover:text-white transition-colors">Features</Link>
                        <Link to="/login" className="text-slate-400 hover:text-white transition-colors">Login</Link>
                    </div>
                    <p className="text-slate-500 text-sm">© 2024 DraftMate. All rights reserved.</p>
                </div>
            </footer>
        </div>
    );
};

export default Disclaimer;
